/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javafinalproject;
/**
 *
 * @author USER
 */
import javax.swing.*;  

public class homepage extends javax.swing.JPanel {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        makeScrollable();
        addAccordionUI1();
        addAccordionUI2();
    }
    
    private void makeScrollable() {
        JPanel contentPanel = new JPanel(null);
        contentPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        // Move GUI components into content panel
        contentPanel.add(jLabel1);
        contentPanel.add(jLabel2);
        contentPanel.add(jLabel3);
        contentPanel.add(apply1);
        contentPanel.add(review1);
        contentPanel.add(apply2);
        contentPanel.add(review2);
        contentPanel.add(apply3);
        contentPanel.add(review3);
        contentPanel.add(apply4);
        contentPanel.add(review4);
        contentPanel.add(apply5);
        contentPanel.add(review5);
        contentPanel.add(apply6);
        contentPanel.add(review6);
        contentPanel.add(jPanel1);
        contentPanel.add(jPanel2);

        // Set manual positions
        jLabel1.setBounds(450, 80, 750, 60);
        jLabel2.setBounds(120, 200, 750, 60);
        jLabel3.setBounds(880, 200, 750, 60);
        apply1.setBounds(570, 385, 150, 40);
        review1.setBounds(570, 440, 150, 40);
        apply2.setBounds(570, 620, 150, 40);
        review2.setBounds(570, 675, 150, 40);
        apply3.setBounds(570, 840, 150, 40);
        review3.setBounds(570, 900, 150, 40);
        apply4.setBounds(1320, 385, 150, 40);
        review4.setBounds(1320, 440, 150, 40);
        apply5.setBounds(1320, 620, 150, 40);
        review5.setBounds(1320, 675, 150, 40);
        apply6.setBounds(1320, 840, 150, 40);
        review6.setBounds(1320, 900, 150, 40);
        jPanel1.setBounds(70, 300, 500, 700);
        jPanel2.setBounds(820, 300, 500, 700);

        // Wrap content inside JScrollPane
        JScrollPane scrollPane = new JScrollPane(contentPanel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);

        // Replace default layout with scrollable one
        setLayout(new java.awt.BorderLayout());
        add(scrollPane, java.awt.BorderLayout.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        apply1 = new javax.swing.JButton();
        review1 = new javax.swing.JButton();
        apply2 = new javax.swing.JButton();
        review2 = new javax.swing.JButton();
        apply3 = new javax.swing.JButton();
        review3 = new javax.swing.JButton();
        apply4 = new javax.swing.JButton();
        review4 = new javax.swing.JButton();
        apply5 = new javax.swing.JButton();
        review5 = new javax.swing.JButton();
        apply6 = new javax.swing.JButton();
        review6 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("STSong", 1, 60)); // NOI18N
        jLabel1.setText("COURSES AVAILABLE");

        jLabel2.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel2.setText("MECHANICAL ENGINEERING DEPARTMENT");

        jLabel3.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel3.setText("ELECTRICAL ENGINEERING DEPARTMENT");

        apply1.setText("apply");
        apply1.setActionCommand("apply1");
        apply1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply1ActionPerformed(evt);
            }
        });

        review1.setText("review");
        review1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review1ActionPerformed(evt);
            }
        });

        apply2.setText("apply");
        apply2.setActionCommand("apply1");
        apply2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply2ActionPerformed(evt);
            }
        });

        review2.setText("review");
        review2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review2ActionPerformed(evt);
            }
        });

        apply3.setText("apply");
        apply3.setActionCommand("apply1");
        apply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply3ActionPerformed(evt);
            }
        });

        review3.setText("review");
        review3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review3ActionPerformed(evt);
            }
        });

        apply4.setText("apply");
        apply4.setActionCommand("apply1");
        apply4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply4ActionPerformed(evt);
            }
        });

        review4.setText("review");
        review4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review4ActionPerformed(evt);
            }
        });

        apply5.setText("apply");
        apply5.setActionCommand("apply1");
        apply5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply5ActionPerformed(evt);
            }
        });

        review5.setText("review");
        review5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review5ActionPerformed(evt);
            }
        });

        apply6.setText("apply");
        apply6.setActionCommand("apply1");
        apply6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply6ActionPerformed(evt);
            }
        });

        review6.setText("review");
        review6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apply1)
                            .addComponent(review1)
                            .addComponent(apply2)
                            .addComponent(review2)
                            .addComponent(apply3)
                            .addComponent(review3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apply6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(review6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(review5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apply5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apply4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(review4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(apply1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(review1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(apply2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(review2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(apply4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(review4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(apply5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(review5)))
                                    .addGap(25, 25, 25))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(apply3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(review3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(apply6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(review6)))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void apply1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply1ActionPerformed
        // TODO add your handling code here:
        miniproject.EmailMain.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_apply1ActionPerformed

    private void review1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review1ActionPerformed
        // TODO add your handling code here:
            // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new coursepreview());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
    }//GEN-LAST:event_review1ActionPerformed

    private void apply2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply2ActionPerformed
        // TODO add your handling code here:
        miniproject.EmailMain.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_apply2ActionPerformed

    private void review2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review2ActionPerformed
        // TODO add your handling code here:
            // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new coursepreview());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_review2ActionPerformed

    private void apply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply3ActionPerformed
        // TODO add your handling code here:
        
        miniproject.EmailMain.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_apply3ActionPerformed

    private void review3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review3ActionPerformed
        // TODO add your handling code here:
            // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new coursepreview());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_review3ActionPerformed

    private void apply4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply4ActionPerformed
        // TODO add your handling code here:
        
        miniproject.EmailMain.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_apply4ActionPerformed

    private void review4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review4ActionPerformed
        // TODO add your handling code here:
            // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new coursepreview2());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_review4ActionPerformed

    private void apply5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply5ActionPerformed
        // TODO add your handling code here:
        miniproject.EmailMain.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_apply5ActionPerformed

    private void review5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review5ActionPerformed
        // TODO add your handling code here:
            // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new coursepreview2());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_review5ActionPerformed

    private void apply6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply6ActionPerformed
        // TODO add your handling code here:
        miniproject.EmailMain.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_apply6ActionPerformed

    private void review6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review6ActionPerformed
        // TODO add your handling code here:
            // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new coursepreview2());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_review6ActionPerformed
    
    private void addAccordionUI1() {
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(createAccordionSection(
            "CNC PRECISION TECHNOLOGY",
            "<html><b>Description:</b><br>" +
            "Introduce to the fundamentals of Computer Numerical Control (CNC) machining. Learn how to operate and program CNC milling and turning machines used in manufacturing industries. The program emphasizes precision measurement, tool handling, and the use of CAD/CAM software for part design and production." +
            "</html>"
        ));


        jPanel1.add(createAccordionSection(
            "MANUFACTURING SYSTEM", 
            "<html><b>Description:</b><br>" +
            "This course focuses on the modern manufacturing process, covering production planning, materials handling, quality control, and lean manufacturing concepts. You’ll gain knowledge on how different processes work together to improve efficiency and reduce waste in production environments." +
            "</html>"
        ));
        jPanel1.add(createAccordionSection(
            "MACHINE TOOL MAINTAINANCE", 
            "<html><b>Description:</b><br>" +
            "Learn how to inspect, maintain, and repair machine tools used in workshops and factories. This course emphasizes preventive maintenance, troubleshooting techniques, and mechanical systems like bearings, hydraulics, and pneumatics. You’ll also gain hands-on experience maintaining lathes, milling machines, and CNC systems." +
            "</html>"
        ));
        
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    private void addAccordionUI2() {
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        jPanel2.add(createAccordionSection(
            "AUTOMATION & IOT", 
            "<html><b>Description:</b><br>" +
            "This course blends industrial automation and Internet of Things (IoT) technology. Students will learn how to use sensors, microcontrollers (like Arduino and ESP32), and PLCs to control systems remotely. You’ll also explore how smart systems are applied in modern factories and homes." +
            "</html>"
        ));
        jPanel2.add(createAccordionSection(
            "COMPUTER & NETWORK", 
            "<html><b>Description:</b><br>" +
            "This course covers the basics of computer systems, networking, and internet technologies. You’ll learn how to set up local area networks (LAN), configure routers and switches, and perform basic troubleshooting. The course also includes practical knowledge on computer maintenance and cybersecurity awareness." +
            "</html>"
        ));
        jPanel2.add(createAccordionSection(
            "ELECTRONIC SYSTEM & COMMUNICATION", 
            "<html><b>Description:</b><br>" +
            "This course introduces students to electronic circuits, communication systems, and microcontrollers. You’ll gain hands-on experience designing and testing electronic projects such as amplifiers, transmitters, and embedded control systems. Perfect for those who want to explore electronics in daily life and industry." +
            "</html>"
        ));
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    private JPanel createAccordionSection(String title, String contentText) {
    JPanel sectionPanel = new JPanel(new java.awt.BorderLayout());
    sectionPanel.setBackground(java.awt.Color.WHITE);

    // Create a JToggleButton with + symbol in front of title
    JToggleButton header = new JToggleButton("  +  " + title);
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
    header.setBackground(new java.awt.Color(245, 245, 245));
    header.setFocusPainted(false);
    header.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
    header.setHorizontalAlignment(SwingConstants.LEFT);

    // Create collapsible content panel
    JPanel content = new JPanel(new java.awt.BorderLayout());
    JLabel label = new JLabel("<html><div style='padding:10px;'>" + contentText + "</div></html>");
    label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    content.add(label, java.awt.BorderLayout.CENTER);
    content.setVisible(false);
    content.setBackground(java.awt.Color.WHITE);

    // Toggle + / - when expanded or collapsed
    header.addActionListener(e -> {
        if (header.isSelected()) {
            header.setText("  -  " + title); // change + to -
            content.setVisible(true);
        } else {
            header.setText("  +  " + title);
            content.setVisible(false);
        }
        sectionPanel.revalidate();
        sectionPanel.repaint();
    });

    // Styling: light border below each section
    sectionPanel.add(header, java.awt.BorderLayout.NORTH);
    sectionPanel.add(content, java.awt.BorderLayout.CENTER);
    sectionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.LIGHT_GRAY));

    return sectionPanel;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apply1;
    private javax.swing.JButton apply2;
    private javax.swing.JButton apply3;
    private javax.swing.JButton apply4;
    private javax.swing.JButton apply5;
    private javax.swing.JButton apply6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton review1;
    private javax.swing.JButton review2;
    private javax.swing.JButton review3;
    private javax.swing.JButton review4;
    private javax.swing.JButton review5;
    private javax.swing.JButton review6;
    // End of variables declaration//GEN-END:variables
}
