/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javafinalproject;
/**
 *
 * @author USER
 */
import javax.swing.*;  

public class overviewpage extends javax.swing.JPanel {

public overviewpage() {
        initComponents();
        makeScrollable();
        addAccordionUI1();
        addAccordionUI2();
    }

    /** Make the entire panel scrollable */
    private void makeScrollable() {
        JPanel contentPanel = new JPanel(null);
        contentPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        // Move GUI components into content panel
        contentPanel.add(jLabel1);
        contentPanel.add(jLabel2);
        contentPanel.add(jLabel3);
        contentPanel.add(jButton1);
        contentPanel.add(jPanel1);
        contentPanel.add(jPanel2);

        // Set manual positions
        jLabel3.setBounds(400, 80, 750, 60);
        jLabel2.setBounds(100, 300, 750, 60);
        jLabel1.setBounds(895, 300, 750, 60);
        jButton1.setBounds(1200, 75, 200, 50);
        jPanel1.setBounds(110, 400, 500, 600);
        jPanel2.setBounds(900, 400, 500, 600);

        // Wrap content inside JScrollPane
        JScrollPane scrollPane = new JScrollPane(contentPanel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);

        // Replace default layout with scrollable one
        setLayout(new java.awt.BorderLayout());
        add(scrollPane, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setText("APPLY NOW!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jLabel1.setText("ELECTRICAL ENGINEERING");

        jLabel2.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jLabel2.setText("MECHANICAL ENGINEERING");

        jLabel3.setFont(new java.awt.Font("STSong", 1, 60)); // NOI18N
        jLabel3.setText("WELCOME TO UCAS GMI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(568, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(550, 550, 550)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(355, 355, 355))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(jLabel3)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Get the parent JFrame that holds this panel
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    // Remove the current panel (overview)
    parentFrame.getContentPane().removeAll();

    // Add the homepage panel
    parentFrame.add(new homepage());

    // Refresh the frame to display the new panel
    parentFrame.revalidate();
    parentFrame.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void addAccordionUI1() {
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(createAccordionSection(
            "CNC PRECISION TECHNOLOGY",
            "<html><b>Description:</b><br>" +
            "Introduce to the fundamentals of Computer Numerical Control (CNC) machining. Learn how to operate and program CNC milling and turning machines used in manufacturing industries. The program emphasizes precision measurement, tool handling, and the use of CAD/CAM software for part design and production." +
            "</html>"
        ));


        jPanel1.add(createAccordionSection(
            "MANUFACTURING SYSTEM", 
            "<html><b>Description:</b><br>" +
            "This course focuses on the modern manufacturing process, covering production planning, materials handling, quality control, and lean manufacturing concepts. You’ll gain knowledge on how different processes work together to improve efficiency and reduce waste in production environments." +
            "</html>"
        ));
        jPanel1.add(createAccordionSection(
            "MACHINE TOOL MAINTAINANCE", 
            "<html><b>Description:</b><br>" +
            "Learn how to inspect, maintain, and repair machine tools used in workshops and factories. This course emphasizes preventive maintenance, troubleshooting techniques, and mechanical systems like bearings, hydraulics, and pneumatics. You’ll also gain hands-on experience maintaining lathes, milling machines, and CNC systems." +
            "</html>"
        ));
        
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    private void addAccordionUI2() {
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        jPanel2.add(createAccordionSection(
            "AUTOMATION & IOT", 
            "<html><b>Description:</b><br>" +
            "This course blends industrial automation and Internet of Things (IoT) technology. Students will learn how to use sensors, microcontrollers (like Arduino and ESP32), and PLCs to control systems remotely. You’ll also explore how smart systems are applied in modern factories and homes." +
            "</html>"
        ));
        jPanel2.add(createAccordionSection(
            "COMPUTER & NETWORK", 
            "<html><b>Description:</b><br>" +
            "This course covers the basics of computer systems, networking, and internet technologies. You’ll learn how to set up local area networks (LAN), configure routers and switches, and perform basic troubleshooting. The course also includes practical knowledge on computer maintenance and cybersecurity awareness." +
            "</html>"
        ));
        jPanel2.add(createAccordionSection(
            "ELECTRONIC SYSTEM & COMMUNICATION", 
            "<html><b>Description:</b><br>" +
            "This course introduces students to electronic circuits, communication systems, and microcontrollers. You’ll gain hands-on experience designing and testing electronic projects such as amplifiers, transmitters, and embedded control systems. Perfect for those who want to explore electronics in daily life and industry." +
            "</html>"
        ));
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    private JPanel createAccordionSection(String title, String contentText) {
    JPanel sectionPanel = new JPanel(new java.awt.BorderLayout());
    sectionPanel.setBackground(java.awt.Color.WHITE);

    // Create a JToggleButton with + symbol in front of title
    JToggleButton header = new JToggleButton("  +  " + title);
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
    header.setBackground(new java.awt.Color(245, 245, 245));
    header.setFocusPainted(false);
    header.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
    header.setHorizontalAlignment(SwingConstants.LEFT);

    // Create collapsible content panel
    JPanel content = new JPanel(new java.awt.BorderLayout());
    JLabel label = new JLabel("<html><div style='padding:10px;'>" + contentText + "</div></html>");
    label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    content.add(label, java.awt.BorderLayout.CENTER);
    content.setVisible(false);
    content.setBackground(java.awt.Color.WHITE);

    // Toggle + / - when expanded or collapsed
    header.addActionListener(e -> {
        if (header.isSelected()) {
            header.setText("  -  " + title); // change + to -
            content.setVisible(true);
        } else {
            header.setText("  +  " + title);
            content.setVisible(false);
        }
        sectionPanel.revalidate();
        sectionPanel.repaint();
    });

    // Styling: light border below each section
    sectionPanel.add(header, java.awt.BorderLayout.NORTH);
    sectionPanel.add(content, java.awt.BorderLayout.CENTER);
    sectionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.LIGHT_GRAY));

    return sectionPanel;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
