package javafinalproject;
import javax.swing.*;  // ✅ Needed for Swing components
public class overviewpage2 extends javax.swing.JPanel {

    public overviewpage() {
        initComponents();
        addAccordionUI(); // ✅ Adds the accordion after GUI loads
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
jPanel1.setName("accordionContainer"); 
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here
    }                                        

    // ✅ Corrected: uses jPanel1 instead of accordionContainer
    private void addAccordionUI() {
        jPanel1.add(createAccordionSection(
                "Section 1: About UCAS",
                "UCAS GMI is a student management system designed for GMI students and staff."
        ));
        jPanel1.add(createAccordionSection(
                "Section 2: Features",
                "It allows student registration, attendance tracking, and grade management."
        ));
        jPanel1.add(createAccordionSection(
                "Section 3: Contact",
                "For help, contact support@gmi.edu.my"
        ));

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    // ✅ Fixed return type
    private JPanel createAccordionSection(String title, String contentText) {
        JPanel sectionPanel = new JPanel(new java.awt.BorderLayout());
        sectionPanel.setBackground(java.awt.Color.WHITE);

        JToggleButton header = new JToggleButton(title);
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        header.setBackground(new java.awt.Color(220, 220, 220));

        JPanel content = new JPanel(new java.awt.BorderLayout());
        JLabel label = new JLabel("<html><div style='padding:10px;'>" + contentText + "</div></html>");
        content.add(label, java.awt.BorderLayout.CENTER);
        content.setVisible(false);
        content.setBackground(java.awt.Color.WHITE);

        header.addActionListener(e -> content.setVisible(header.isSelected()));

        sectionPanel.add(header, java.awt.BorderLayout.NORTH);
        sectionPanel.add(content, java.awt.BorderLayout.CENTER);
        sectionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.LIGHT_GRAY));

        return sectionPanel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
